// Puente seguro entre la UI y el proceso main.
// Expone SOLO funciones de negocio; nunca el certificado ni Node directo.

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  emisor: () => ipcRenderer.invoke("app:emisor"),
  setupEstado: () => ipcRenderer.invoke("setup:estado"),
  setupElegirArchivo: (tipo) => ipcRenderer.invoke("setup:elegirArchivo", tipo),
  setupGuardar: (data) => ipcRenderer.invoke("setup:guardar", data),
  serverStatus: () => ipcRenderer.invoke("arca:serverStatus"),
  proximoNumero: (ptoVta, cbteTipo) => ipcRenderer.invoke("arca:proximoNumero", ptoVta, cbteTipo),
  consultarPadron: (cuit) => ipcRenderer.invoke("padron:consultar", cuit),
  emitir: (opts) => ipcRenderer.invoke("factura:emitir", opts),
  emitirNota: (opts) => ipcRenderer.invoke("factura:nota", opts),
  listarFacturas: (q) => ipcRenderer.invoke("facturas:listar", q),
  imprimirFactura: (id, copias) => ipcRenderer.invoke("factura:imprimir", id, copias),
  crearPresupuesto: (opts) => ipcRenderer.invoke("presupuesto:crear", opts),
  listarPresupuestos: (q) => ipcRenderer.invoke("presupuestos:listar", q),
  imprimirPresupuesto: (id) => ipcRenderer.invoke("presupuesto:imprimir", id),
  facturarPresupuesto: (id) => ipcRenderer.invoke("presupuesto:facturar", id),
  eliminarPresupuesto: (id) => ipcRenderer.invoke("presupuesto:eliminar", id),
  compartirPresupuesto: (opts) => ipcRenderer.invoke("presupuesto:compartir", opts),
  sincronizar: () => ipcRenderer.invoke("nube:sincronizar"),
  nubeEstadoSync: () => ipcRenderer.invoke("nube:estado"),
  exportarDatos: () => ipcRenderer.invoke("datos:exportar"),
  metricas: () => ipcRenderer.invoke("app:metricas"),
  listarPedidos: () => ipcRenderer.invoke("pedidos:listar"),
  pedidoDetalle: (id) => ipcRenderer.invoke("pedido:detalle", id),
  facturarPedido: (id, receptor) => ipcRenderer.invoke("pedido:facturar", id, receptor),
  resumen: () => ipcRenderer.invoke("app:resumen"),
  listarClientes: (q) => ipcRenderer.invoke("clientes:listar", q),
  guardarCliente: (c) => ipcRenderer.invoke("clientes:guardar", c),
  eliminarCliente: (cuit) => ipcRenderer.invoke("clientes:eliminar", cuit),
  reporteDatos: (filtro) => ipcRenderer.invoke("reporte:datos", filtro),
  reporteExportar: (filtro) => ipcRenderer.invoke("reporte:exportar", filtro),
  compartirFactura: (opts) => ipcRenderer.invoke("factura:compartir", opts),
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (patch) => ipcRenderer.invoke("config:set", patch),
  // Credenciales de la nube (por PC)
  cloudEstadoCred: () => ipcRenderer.invoke("cloud:estadoCred"),
  cloudProbarCred: (c) => ipcRenderer.invoke("cloud:probarCred", c),
  cloudGuardarCred: (c) => ipcRenderer.invoke("cloud:guardarCred", c),
  listarImpresoras: () => ipcRenderer.invoke("impresoras:listar"),
  elegirCarpeta: () => ipcRenderer.invoke("dialog:elegirCarpeta"),
  // ---- Sancor ----
  sancorCarpetaBase: () => ipcRenderer.invoke("sancor:carpetaBase"),
  sancorElegirCarpetaBase: () => ipcRenderer.invoke("sancor:elegirCarpetaBase"),
  sancorElegirPreliqs: () => ipcRenderer.invoke("sancor:elegirPreliqs"),
  sancorAnalizar: (srcPath) => ipcRenderer.invoke("sancor:analizar", srcPath),
  sancorProcesar: (opts) => ipcRenderer.invoke("sancor:procesar", opts),
  sancorEmitirFactura: (opts) => ipcRenderer.invoke("sancor:emitirFactura", opts),
  sancorAbrirCarpeta: (carpeta) => ipcRenderer.invoke("sancor:abrirCarpeta", carpeta),
  sancorAgregarFotos: (opts) => ipcRenderer.invoke("sancor:agregarFotos", opts),
  sancorGuardarFotos: (opts) => ipcRenderer.invoke("sancor:guardarFotos", opts),
  sancorNubeEstado: () => ipcRenderer.invoke("sancor:nubeEstado"),
  sancorDescargarMes: (opts) => ipcRenderer.invoke("sancor:descargarMes", opts),
});
